# Generated by Django 4.0.3 on 2022-04-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
    ]
