# Generated by Django 4.0.3 on 2022-04-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_post_hashtags_alter_post_caption_alter_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
