# Generated by Django 4.0.3 on 2022-04-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
