# Generated by Django 4.0.3 on 2022-04-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_alter_post_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.CharField(blank=True, default='#', max_length=200),
        ),
    ]
